#
# NDSLabs cluster on OpenStack - deploy ndslabs on kubernetes
#
- name: setup ansible host vars
  hosts: all
  roles:
    - pre-checks
    - ansible_host_vars_setup

- name: include site vars
  hosts: cluster
  tasks:
    - include_vars: "{{ inventory_dir }}/site_vars/{{ site }}.yml"

# Apply Kubernetes node labels for NDS - 
- name: label K8s nodes
  hosts: nodes
  roles:
    - ndslabs-k8-init-labels

# Docker cache - RC count 1 with host vol,
- name: Docker cache k8s files
  hosts: masters[0]
  roles:
    - k8s-local-docker-cache
- name: docker cache config on nodes 
  hosts: cluster
  roles:
    - k8s-local-docker-cache-nodeconfig

# Deploy global FS - state directories
- name: glfs state directories
  hosts: cluster
  become: true
  tasks:
    - file: path="/var/glfs" state=directory
    - file: path="/var/lib/glusterd" state=directory
    - file: path="/var/log/glusterfs" state=directory
    - file: path="/etc/glusterfs" state=directory
    - file: path="/var/lib/xfsdump" state=directory

- name: Global FS k8s objects
  hosts: glfs
  roles:
    - { role: k8-glfs-server-pods, when: "'glfs' in groups and groups['glfs']|length > 0" }

- name: Global FS k8s objects
  hosts: masters[0]
  roles:
    - { role: k8-glfs-client-set, when: "'glfs' in groups and groups['glfs']|length > 0" }

# Fix publicip nodes
- name: LoadBalancer public interface
  hosts: publicip
  connection: local
  tasks:
    - os_floating_ip: server={{ logical_cluster_name }}-{{ inventory_hostname }} reuse=yes wait=yes
    - command: openstack server add security group {{ logical_cluster_name }}-{{ inventory_hostname }} {{ security_groups }}


# Create or reuse existing TLS certs
- name: Generate TLS certificates
  hosts: cluster
  connection: local
  run_once: true
  roles: 
    - generate-tls-certs

# Import TLS certs as kubernetes secrets
- name: Create TLS secret
  hosts: masters
  run_once: true
  roles: 
    - k8-tls-secret

# Deploy Kubernetes Addons: DNS + LMA
- name: Kubernetes Cluster Add-ons | ndslabs flavor
  hosts: masters
  roles:
    - cluster-addons

# Nagios NRPE client
- name: Nagios NRPE client
  hosts: masters[0]
  roles:
    - k8s-nagios-nrpe 

# Deploy NDS Labs and LoadBalancer  
- name: Start NDSLabs ApiServer and WebUI
  hosts: masters[0]
  roles:
    - ndslabs-api-gui
    - ndslabs-loadbalancer

# Add the cluster-local registry, mapped to all hosts on localhost:5000
- name: registry storage
  hosts: compute[0]
  become: true
  tasks:
    - file: path="{{ clusterfs_vol_path }}/docker-registry" state=directory 

- name: cluster-local-docker-registry
  hosts: masters[0]
  roles:
    - k8s-local-docker-registry
